BookList/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BookList.Models
{
    public class Book
    {
        [Key]
        public int BookId { get; set; }

        [Required(ErrorMessage = "This field cannot be null")]
        public string BookName { get; set; }

        public string BookAuthor { get; set; }

        public string ISBN { get; set; }
    }
}

BookList/Models/BookListDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookList.Models
{
    public class BookListDbContext:DbContext
    {
        public BookListDbContext(DbContextOptions<BookListDbContext> options):base(options)
        {
        }

        public DbSet<Book> Book { get; set; }
    }
}

BookList/Controllers/BookController.cs
using BookList.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookList.Controllers
{

    [Route("api/Book")]
    [ApiController]
    public class BookController : Controller
    {

        private readonly BookListDbContext _db;

        public BookController(BookListDbContext db)
        {
            _db = db;
        }

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _db.Book.ToListAsync() });
        }

        //-----

        public async Task<IActionResult> Delete(int id)
        {
            var dbCurrentBook = await _db.Book.FirstOrDefaultAsync(x=>x.BookId==id);

            if (dbCurrentBook == null)
            {
                return Json(new{success=false, message="The book was could not be deleted"});
            }
            else
            {
                _db.Book.Remove(dbCurrentBook);
                await _db.SaveChangesAsync();
                return Json(new { success=true, message = "The book was removed" });
            }
        }
    }
}

BookList/Pages/BookList/CreateBook.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookList.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookList.Pages.BookList
{
    public class CreateBookModel : PageModel
    {

        private readonly BookListDbContext _db;
        public CreateBookModel(BookListDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public Book Book { get; set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                await _db.Book.AddAsync(Book);
                await _db.SaveChangesAsync();

                return RedirectToPage("Index");
            }
            else
            {
                return Page(); // load current page
            }
        }
    }
}

BookList/Pages/BookList/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookList.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookList.Pages.BookList
{
    public class EditModel : PageModel
    {

        private BookListDbContext _db;

        public EditModel(BookListDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public Book Book { get; set; }

        public async Task OnGet(int id)
        {
            Book = await _db.Book.FindAsync(id);
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var currentBook = await _db.Book.FindAsync(Book.BookId);
                currentBook.BookName = Book.BookName;
                currentBook.BookAuthor = Book.BookAuthor;
                currentBook.ISBN = Book.ISBN;

                await _db.SaveChangesAsync();

                return RedirectToPage("Index");
            }
            else
            {
                return RedirectToPage();
            }
        }

    }
}

BookList/Pages/BookList/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookList.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace BookList.Pages.BookList
{
    public class IndexModel : PageModel
    {

        private readonly BookListDbContext _db;

        public IndexModel(BookListDbContext db)
        {
            _db = db;
        }

        public IEnumerable<Book> Books { get; set; }

        public async Task OnGet()
        {
            Books = await _db.Book.ToListAsync();            
        }

        public async Task<IActionResult> OnPostDelete(int id)
        {
            var book = await _db.Book.FindAsync(id);

            if (book == null)
            {
                return NotFound();
            }
            else
            {
                _db.Book.Remove(book);
                await _db.SaveChangesAsync();
                return RedirectToPage("Index");
            }

        }
    }
}

BookList/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BookList.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

BookList/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookList.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

BookList/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookList.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

BookList/Pages/BookList/CreateBook.cshtml
@page
@model BookList.Pages.BookList.CreateBookModel

<br />
<h2> Create New Book</h2>
<br />

<div class="border container" style="padding:30px;">
    <form method="post">

        <div class="text-danger" asp-validation-summary="ModelOnly">

        </div>

        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Book.BookName"></label>
            </div>
            <div class="col-6">
                <input asp-for="Book.BookName" class="form-control" />
            </div>
            <span asp-validation-for="Book.BookName" class="text-danger"></span>
        </div>
        <div class="form-group row">

            <div class="col-3">
                <label asp-for="Book.BookAuthor"></label>
            </div>
            <div class="col-6">
                <input asp-for="Book.BookAuthor" class="form-control" />
            </div>
            <span asp-validation-for="Book.BookAuthor" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Book.ISBN"></label>
            </div>
            <div class="col-6">
                <input asp-for="Book.ISBN" class="form-control" />
            </div>
            <span asp-validation-for="Book.ISBN" class="text-danger"></span>
        </div>

        <div class="form-group row">
            <div class="col-3 offset-3">
                <input type="submit" value="Create" class="btn btn-primary form-control" />
            </div>
            <div class="col-3">
                <a asp-page="Index" class="btn btn-success form-control"> Back Book List</a>
            </div>
        </div>
    </form>
</div>

@section Scripts{ 
<partial name="_ValidationScriptsPartial" />
}

BookList/Pages/BookList/Edit.cshtml
@page
@model BookList.Pages.BookList.EditModel

<br />
<h2> Edit Book</h2>
<br />

<div class="border container" style="padding:30px;">
    <form method="post">

        <input type="hidden" asp-for="Book.BookId"/>

        <div class="text-danger" asp-validation-summary="ModelOnly">
        </div>

        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Book.BookName"></label>
            </div>
            <div class="col-6">
                <input asp-for="Book.BookName" class="form-control" />
            </div>
            <span asp-validation-for="Book.BookName" class="text-danger"></span>
        </div>
        <div class="form-group row">

            <div class="col-3">
                <label asp-for="Book.BookAuthor"></label>
            </div>
            <div class="col-6">
                <input asp-for="Book.BookAuthor" class="form-control" />
            </div>
            <span asp-validation-for="Book.BookAuthor" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Book.ISBN"></label>
            </div>
            <div class="col-6">
                <input asp-for="Book.ISBN" class="form-control" />
            </div>
            <span asp-validation-for="Book.ISBN" class="text-danger"></span>
        </div>

        <div class="form-group row">
            <div class="col-3 offset-3">
                <input type="submit" value="Edit" class="btn btn-primary form-control" />
            </div>
            <div class="col-3">
                <a asp-page="Index" class="btn btn-success form-control"> Back Book List</a>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

BookList/Pages/BookList/Index.cshtml
@page

@model BookList.Pages.BookList.IndexModel
@{
    ViewData["Title"] = "Index";
}

<div class="container row p-0 m-0">

    <div class="col-9">
        <h2 class="text-info">Book List</h2>
    </div>

    <div class="col-3">
        <a asp-page="CreateBook" class="btn btn-info form-control text-white">Create New Book</a>
    </div>

    <div class="col-12 border p-3 mt-3">
        <form method="post">
            @if (Model.Books.Count() > 0)
            {
                <table class="table table-striped border">
                    <tr class="table-secondary">
                        <th>
                            <label asp-for="Books.FirstOrDefault().BookName"></label>
                        </th>
                        <th>
                            @*@Html.DisplayNameFor(n => n.Books.FirstOrDefault().BookAuthor)*@
                            <label asp-for="Books.FirstOrDefault().BookAuthor"></label>
                        </th>
                        <th>
                            <label asp-for="Books.FirstOrDefault().ISBN"></label>
                        </th>
                        <th></th>

                    </tr>

                    @foreach (var book in Model.Books)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(a => book.BookName)
                            </td>

                            <td>
                                @Html.DisplayFor(a => book.BookAuthor)
                            </td>

                            <td>
                                @Html.DisplayFor(a => book.ISBN)
                            </td>

                            <td>
                                <a asp-page="Edit" asp-route-id="@book.BookId" class="btn btn-success btn-sm text-white">Edit</a>
                                <button asp-page-handler="Delete" asp-route-id="@book.BookId" onclick="return confirm('This book will be removed. Are you sure?')" class="btn btn-danger btn-sm">Delete</button>
                            </td>
                        </tr>
                    }

                </table>
            }
            else
            {
                <p>Any books cannot be found</p>
            }
        </form>
    </div>

    <div class="col-12" style="text-align:center">
        <br />
        <span class="h3 text-info">2.Area</span>
        <br />
        <br />
    </div>

    <div class="col-12 border p-3">
        <table id="DT_load" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Book Name</th>
                    <th>Author</th>
                    <th>ISBN</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>

</div>

@section Scripts{
    <script src="~/js/BookList.js"></script>
}

BookList/Pages/BookList/Index1.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

BookList/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BookList/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">

    @*<link rel="stylesheet" href="sweetalert2.min.css">*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css">
    
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/datatables/datatables.min.css" rel="stylesheet" />
    <link href="~/jquery/jquery-ui.min.css" rel="stylesheet" />
    @*<link href="~/sweetalert/sweetalert2.min.css" rel="stylesheet" />*@
    @*<link href="~/toastr/toastr.min.css" rel="stylesheet" />*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">BookList</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/BookList/Index">Books</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - BookList - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

    @*<script src="sweetalert2.min.js"></script>*@
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/datatables/datatables.min.js"></script>
    <script src="~/jquery/jquery-ui.min.js"></script>
    @*<script src="~/sweetalert/sweetalert2.min.js"></script>*@
    @*<script src="~/toastr/toastr.min.js"></script>*@

    @RenderSection("Scripts", required: false)
</body>
</html>